/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Si el usuario tiene doble factor, devuelve un desafío en vez del token:
         *     el token llega después, en /auth/mfa/verificar.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verificar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verificar Mfa */
        post: operations["verificar_mfa_api_v1_auth_mfa_verificar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yo */
        get: operations["yo_api_v1_auth_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar Mfa */
        post: operations["iniciar_mfa_api_v1_auth_mfa_iniciar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar Mfa
         * @description Activar el doble factor cierra las sesiones abiertas con solo contraseña.
         *     Devuelve una nueva para quien lo acaba de activar: acaba de demostrar que
         *     tiene el teléfono.
         */
        post: operations["confirmar_mfa_api_v1_auth_mfa_confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cambiar-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Password
         * @description Cierra todas las sesiones, incluida esta: hay que volver a ingresar.
         */
        post: operations["cambiar_password_api_v1_auth_cambiar_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recuperar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar
         * @description Responde igual exista o no el correo.
         */
        post: operations["recuperar_api_v1_auth_recuperar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/restablecer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablecer */
        post: operations["restablecer_api_v1_auth_restablecer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v1_usuarios_get"];
        put?: never;
        /** Crear */
        post: operations["crear_api_v1_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar */
        patch: operations["editar_api_v1_usuarios__usuario_id__patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/restablecer-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablecer Password */
        post: operations["restablecer_password_api_v1_usuarios__usuario_id__restablecer_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/reiniciar-mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reiniciar Mfa
         * @description Reinicia el doble factor y la contraseña a la vez: ver services.usuarios.reiniciar_mfa.
         */
        post: operations["reiniciar_mfa_api_v1_usuarios__usuario_id__reiniciar_mfa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles */
        get: operations["roles_api_v1_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CambioPasswordEntrada */
        CambioPasswordEntrada: {
            /** Actual */
            actual: string;
            /** Nueva */
            nueva: string;
        };
        /** CodigoEntrada */
        CodigoEntrada: {
            /**
             * Codigo
             * @description Código de 6 dígitos de la aplicación autenticadora
             */
            codigo: string;
        };
        /** DesafioMfa */
        DesafioMfa: {
            /**
             * Requiere Mfa
             * @default true
             * @constant
             */
            requiere_mfa: true;
            /** Token Mfa */
            token_mfa: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginEntrada */
        LoginEntrada: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MfaInicioSalida */
        MfaInicioSalida: {
            /**
             * Secreto
             * @description Para escribirlo a mano si no se puede escanear el QR
             */
            secreto: string;
            /**
             * Uri
             * @description otpauth:// para generar el código QR
             */
            uri: string;
        };
        /** PasswordTemporalSalida */
        PasswordTemporalSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /**
             * Password Temporal
             * @description Se muestra una sola vez. Entregarla por un canal seguro.
             */
            password_temporal: string;
        };
        /** RecuperarEntrada */
        RecuperarEntrada: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** RestablecerEntrada */
        RestablecerEntrada: {
            /** Token */
            token: string;
            /** Nueva */
            nueva: string;
        };
        /** RolSalida */
        RolSalida: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Permisos */
            permisos: string[];
        };
        /** SegundoFactorEntrada */
        SegundoFactorEntrada: {
            /** Token Mfa */
            token_mfa: string;
            /**
             * Codigo
             * @description Código de 6 dígitos de la aplicación autenticadora
             */
            codigo: string;
        };
        /** TokenSalida */
        TokenSalida: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expira En Segundos */
            expira_en_segundos: number;
        };
        /** UsuarioCrear */
        UsuarioCrear: {
            /** Nombre */
            nombre: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Rol */
            rol: string;
            /**
             * Alcance
             * @default todos
             * @enum {string}
             */
            alcance: "todos" | "asignados" | "propios";
        };
        /** UsuarioEditar */
        UsuarioEditar: {
            /** Nombre */
            nombre?: string | null;
            /** Rol */
            rol?: string | null;
            /** Activo */
            activo?: boolean | null;
            /** Alcance */
            alcance?: ("todos" | "asignados" | "propios") | null;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Alcance */
            alcance: string;
            /** Activo */
            activo: boolean;
            /** Mfa Habilitado */
            mfa_habilitado: boolean;
            /** Debe Cambiar Password */
            debe_cambiar_password: boolean;
            /** Bloqueado */
            bloqueado: boolean;
            /** Ultimo Acceso */
            ultimo_acceso: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YoSalida */
        YoSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Alcance */
            alcance: string;
            /** Permisos */
            permisos: string[];
            /** Mfa Habilitado */
            mfa_habilitado: boolean;
            /** Debe Cambiar Password */
            debe_cambiar_password: boolean;
            /**
             * Mfa Requerido
             * @description Su rol exige doble factor y aún no lo activa
             */
            mfa_requerido: boolean;
            /** Ultimo Acceso */
            ultimo_acceso: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"] | components["schemas"]["DesafioMfa"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verificar_mfa_api_v1_auth_mfa_verificar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegundoFactorEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yo_api_v1_auth_yo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YoSalida"];
                };
            };
        };
    };
    iniciar_mfa_api_v1_auth_mfa_iniciar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaInicioSalida"];
                };
            };
        };
    };
    confirmar_mfa_api_v1_auth_mfa_confirmar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodigoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_password_api_v1_auth_cambiar_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioPasswordEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recuperar_api_v1_auth_recuperar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecuperarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_api_v1_auth_restablecer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestablecerEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_usuarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"][];
                };
            };
        };
    };
    crear_api_v1_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_api_v1_usuarios__usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_password_api_v1_usuarios__usuario_id__restablecer_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reiniciar_mfa_api_v1_usuarios__usuario_id__reiniciar_mfa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roles_api_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolSalida"][];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
