/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Si el usuario tiene doble factor, devuelve un desafío en vez del token:
         *     el token llega después, en /auth/mfa/verificar.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verificar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verificar Mfa */
        post: operations["verificar_mfa_api_v1_auth_mfa_verificar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yo */
        get: operations["yo_api_v1_auth_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar Mfa */
        post: operations["iniciar_mfa_api_v1_auth_mfa_iniciar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar Mfa
         * @description Activar el doble factor cierra las sesiones abiertas con solo contraseña.
         *     Devuelve una nueva para quien lo acaba de activar: acaba de demostrar que
         *     tiene el teléfono.
         */
        post: operations["confirmar_mfa_api_v1_auth_mfa_confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cambiar-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Password
         * @description Cierra todas las sesiones, incluida esta: hay que volver a ingresar.
         */
        post: operations["cambiar_password_api_v1_auth_cambiar_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recuperar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar
         * @description Responde igual exista o no el correo.
         */
        post: operations["recuperar_api_v1_auth_recuperar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/restablecer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablecer */
        post: operations["restablecer_api_v1_auth_restablecer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Tablero operativo (RF-022): por estado, responsable, país, origen y riesgo.
         */
        get: operations["listar_api_v1_casos_get"];
        put?: never;
        /** Crear */
        post: operations["crear_api_v1_casos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen */
        get: operations["resumen_api_v1_casos_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/{caso_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle */
        get: operations["detalle_api_v1_casos__caso_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar */
        patch: operations["editar_api_v1_casos__caso_id__patch"];
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Estado
         * @description Avanza el trámite respetando el orden de los estados (RF-023).
         */
        post: operations["cambiar_estado_api_v1_casos__caso_id__estado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/resultado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Resultado
         * @description RF-027. El resultado se registra aunque el trámite siga abierto: una visa
         *     negada puede tener pendiente la entrega del pasaporte (RN-06).
         */
        post: operations["registrar_resultado_api_v1_casos__caso_id__resultado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial
         * @description Cada cambio del trámite, con quién lo hizo. Solo crece (RF-028).
         *
         *     Los códigos y los ids se traducen aquí, contra los catálogos, para que la
         *     pantalla no tenga que adivinar qué es «sede_id: — → 2».
         */
        get: operations["historial_api_v1_casos__caso_id__historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/citas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agendar Cita
         * @description RF-024. La hora se guarda con zona horaria y se muestra en la del usuario (RN-10).
         */
        post: operations["agendar_cita_api_v1_casos__caso_id__citas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/citas/{cita_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Cita */
        patch: operations["actualizar_cita_api_v1_citas__cita_id__patch"];
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/checklist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marcar Checklist */
        post: operations["marcar_checklist_api_v1_casos__caso_id__checklist__item_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogos */
        get: operations["catalogos_api_v1_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v1_clientes_get"];
        put?: never;
        /** Crear */
        post: operations["crear_api_v1_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/verificar-duplicados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verificar Duplicados
         * @description Se consulta antes de guardar: advierte, no bloquea (RF-002).
         */
        post: operations["verificar_duplicados_api_v1_clientes_verificar_duplicados_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle */
        get: operations["detalle_api_v1_clientes__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar */
        patch: operations["editar_api_v1_clientes__cliente_id__patch"];
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/archivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archivar */
        post: operations["archivar_api_v1_clientes__cliente_id__archivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/duplicados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Duplicados De */
        get: operations["duplicados_de_api_v1_clientes__cliente_id__duplicados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/fusionar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fusionar
         * @description Une dos fichas. Exige el permiso de eliminar clientes, que hoy solo tiene
         *     la administradora: RF-002 pide que la fusión sea autorizada.
         */
        post: operations["fusionar_api_v1_clientes__cliente_id__fusionar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Grupo */
        post: operations["crear_grupo_api_v1_grupos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Solicitantes */
        get: operations["listar_solicitantes_api_v1_solicitantes_get"];
        put?: never;
        /** Crear Solicitante */
        post: operations["crear_solicitante_api_v1_solicitantes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitantes/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Por Pasaporte
         * @description Búsqueda exacta por pasaporte sobre la columna cifrada (RF-029).
         */
        get: operations["buscar_por_pasaporte_api_v1_solicitantes_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solicitantes/{solicitante_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar Solicitante */
        patch: operations["editar_solicitante_api_v1_solicitantes__solicitante_id__patch"];
        trace?: never;
    };
    "/api/v1/solicitantes/{solicitante_id}/pasaporte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver Pasaporte
         * @description Devuelve el pasaporte completo y deja constancia de quién lo consultó (RNF-04).
         */
        get: operations["ver_pasaporte_api_v1_solicitantes__solicitante_id__pasaporte_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar
         * @description Una sola caja de búsqueda para todo el sistema (RF-029).
         */
        get: operations["buscar_api_v1_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/ficha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha 360
         * @description RF-005: el cliente, quiénes viajan con él, sus trámites, sus próximas
         *     citas y la cronología, en una sola pantalla.
         */
        get: operations["ficha_360_api_v1_clientes__cliente_id__ficha_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clientes/{cliente_id}/notas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anotar Cliente
         * @description Deja constancia de una llamada, un WhatsApp o una nota (RF-012).
         */
        post: operations["anotar_cliente_api_v1_clientes__cliente_id__notas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casos/{caso_id}/notas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anotar Caso */
        post: operations["anotar_caso_api_v1_casos__caso_id__notas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v1_usuarios_get"];
        put?: never;
        /** Crear */
        post: operations["crear_api_v1_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar */
        patch: operations["editar_api_v1_usuarios__usuario_id__patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/restablecer-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restablecer Password */
        post: operations["restablecer_password_api_v1_usuarios__usuario_id__restablecer_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/reiniciar-mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reiniciar Mfa
         * @description Reinicia el doble factor y la contraseña a la vez: ver services.usuarios.reiniciar_mfa.
         */
        post: operations["reiniciar_mfa_api_v1_usuarios__usuario_id__reiniciar_mfa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/asignables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asignables
         * @description Para el desplegable de responsable. No expone la gestión de usuarios.
         */
        get: operations["asignables_api_v1_usuarios_asignables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles */
        get: operations["roles_api_v1_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CambioEstado */
        CambioEstado: {
            /** Codigo Destino */
            codigo_destino: string;
            /** Motivo */
            motivo?: string | null;
            /** @description Datos que faltan para poder avanzar */
            cambios?: components["schemas"]["CasoEditar"] | null;
            /** Resultado */
            resultado?: ("aprobada" | "negada" | "proceso_administrativo" | "cancelado" | "no_continuo") | null;
            /** Resultado Fecha */
            resultado_fecha?: string | null;
            /**
             * Forzar
             * @description Saltarse el orden de los estados. Exige motivo y permiso de administradora; queda como excepción.
             * @default false
             */
            forzar: boolean;
        };
        /** CambioPasswordEntrada */
        CambioPasswordEntrada: {
            /** Actual */
            actual: string;
            /** Nueva */
            nueva: string;
        };
        /** CasoCrear */
        CasoCrear: {
            /** Solicitante Id */
            solicitante_id: number;
            /** Pais Id */
            pais_id: number;
            /** Tipo Visa Id */
            tipo_visa_id?: number | null;
            /** Modalidad Id */
            modalidad_id?: number | null;
            /** Sede Id */
            sede_id?: number | null;
            /** Responsable Id */
            responsable_id?: number | null;
            /**
             * Negocio Id
             * @description La venta, si ya está registrada
             */
            negocio_id?: number | null;
            /**
             * Id Externo
             * @description N.º de solicitud del SaaS
             */
            id_externo?: string | null;
            /** Fuente */
            fuente?: ("saas" | "manual" | "hibrido") | null;
            /** Proxima Accion */
            proxima_accion?: string | null;
            /** Proxima Accion Fecha */
            proxima_accion_fecha?: string | null;
        };
        /** CasoDetalle */
        CasoDetalle: {
            /** Id */
            id: number;
            /** Solicitante Id */
            solicitante_id: number;
            /** Solicitante */
            solicitante: string;
            /** Estado */
            estado: string;
            /** Estado Nombre */
            estado_nombre: string;
            /** Es Final */
            es_final: boolean;
            /** Responsable */
            responsable: string | null;
            /** Responsable Id */
            responsable_id: number | null;
            /** Pais */
            pais: string | null;
            /**
             * Fuente
             * @enum {string}
             */
            fuente: "saas" | "manual" | "hibrido";
            /** Id Externo */
            id_externo: string | null;
            /** Resultado */
            resultado: ("aprobada" | "negada" | "proceso_administrativo" | "cancelado" | "no_continuo") | null;
            /** Proxima Accion */
            proxima_accion: string | null;
            /** Proxima Accion Fecha */
            proxima_accion_fecha: string | null;
            /** Dias Sin Movimiento */
            dias_sin_movimiento: number;
            /**
             * Riesgo
             * @enum {string}
             */
            riesgo: "ninguno" | "bajo" | "medio" | "alto";
            /** Sin Venta */
            sin_venta: boolean;
            /**
             * Ultima Actividad En
             * Format: date-time
             */
            ultima_actividad_en: string;
            /** Pais Id */
            pais_id: number | null;
            /** Tipo Visa Id */
            tipo_visa_id: number | null;
            /** Modalidad Id */
            modalidad_id: number | null;
            /** Sede Id */
            sede_id: number | null;
            /** Negocio Id */
            negocio_id: number | null;
            /** Etapa Saas */
            etapa_saas: string | null;
            /** Resultado Fecha */
            resultado_fecha: string | null;
            /** Resultado Nota */
            resultado_nota: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /**
             * Citas
             * @default []
             */
            citas: components["schemas"]["CitaSalida"][];
            /**
             * Checklist
             * @default []
             */
            checklist: components["schemas"]["ItemChecklist"][];
            /**
             * Estados Posibles
             * @default []
             */
            estados_posibles: components["schemas"]["EstadoPosible"][];
        };
        /** CasoEditar */
        CasoEditar: {
            /** Pais Id */
            pais_id?: number | null;
            /** Tipo Visa Id */
            tipo_visa_id?: number | null;
            /** Modalidad Id */
            modalidad_id?: number | null;
            /** Sede Id */
            sede_id?: number | null;
            /** Responsable Id */
            responsable_id?: number | null;
            /** Negocio Id */
            negocio_id?: number | null;
            /** Proxima Accion */
            proxima_accion?: string | null;
            /** Proxima Accion Fecha */
            proxima_accion_fecha?: string | null;
        };
        /** CasoSalida */
        CasoSalida: {
            /** Id */
            id: number;
            /** Solicitante Id */
            solicitante_id: number;
            /** Solicitante */
            solicitante: string;
            /** Estado */
            estado: string;
            /** Estado Nombre */
            estado_nombre: string;
            /** Es Final */
            es_final: boolean;
            /** Responsable */
            responsable: string | null;
            /** Responsable Id */
            responsable_id: number | null;
            /** Pais */
            pais: string | null;
            /**
             * Fuente
             * @enum {string}
             */
            fuente: "saas" | "manual" | "hibrido";
            /** Id Externo */
            id_externo: string | null;
            /** Resultado */
            resultado: ("aprobada" | "negada" | "proceso_administrativo" | "cancelado" | "no_continuo") | null;
            /** Proxima Accion */
            proxima_accion: string | null;
            /** Proxima Accion Fecha */
            proxima_accion_fecha: string | null;
            /** Dias Sin Movimiento */
            dias_sin_movimiento: number;
            /**
             * Riesgo
             * @enum {string}
             */
            riesgo: "ninguno" | "bajo" | "medio" | "alto";
            /** Sin Venta */
            sin_venta: boolean;
            /**
             * Ultima Actividad En
             * Format: date-time
             */
            ultima_actividad_en: string;
        };
        /** Catalogos */
        Catalogos: {
            /** Paises */
            paises: components["schemas"]["Opcion"][];
            /** Tipos Visa */
            tipos_visa: components["schemas"]["Opcion"][];
            /** Sedes */
            sedes: components["schemas"]["Opcion"][];
            /** Modalidades */
            modalidades: components["schemas"]["Opcion"][];
            /** Servicios */
            servicios: components["schemas"]["Opcion"][];
            /** Estados Operativos */
            estados_operativos: components["schemas"]["Opcion"][];
            /** Estados Comerciales */
            estados_comerciales: components["schemas"]["Opcion"][];
        };
        /** CitaCrear */
        CitaCrear: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "cas" | "biometria" | "entrevista" | "radicacion" | "preparacion" | "entrega" | "otra";
            /**
             * Inicia En
             * Format: date-time
             */
            inicia_en: string;
            /** Sede Id */
            sede_id?: number | null;
            /**
             * Zona Horaria
             * @default America/Bogota
             */
            zona_horaria: string;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** CitaEditar */
        CitaEditar: {
            /** Estado */
            estado?: ("pendiente" | "programada" | "confirmada" | "reprogramada" | "realizada" | "cancelada") | null;
            /** Inicia En */
            inicia_en?: string | null;
            /** Sede Id */
            sede_id?: number | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** CitaProxima */
        CitaProxima: {
            /** Id */
            id: number;
            /** Caso Id */
            caso_id: number;
            /** Solicitante */
            solicitante: string;
            /** Tipo */
            tipo: string;
            /**
             * Inicia En
             * Format: date-time
             */
            inicia_en: string;
            /** Estado */
            estado: string;
            /** Sede */
            sede: string | null;
        };
        /** CitaSalida */
        CitaSalida: {
            /** Id */
            id: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "cas" | "biometria" | "entrevista" | "radicacion" | "preparacion" | "entrega" | "otra";
            /** Sede Id */
            sede_id: number | null;
            /**
             * Inicia En
             * Format: date-time
             */
            inicia_en: string;
            /** Zona Horaria */
            zona_horaria: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "pendiente" | "programada" | "confirmada" | "reprogramada" | "realizada" | "cancelada";
            /** Observaciones */
            observaciones: string | null;
        };
        /** ClienteCrear */
        ClienteCrear: {
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Numero Documento */
            numero_documento?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Pais Id */
            pais_id?: number | null;
            /** Canal Id */
            canal_id?: number | null;
            /**
             * Consentimiento
             * @default false
             */
            consentimiento: boolean;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** ClienteDetalle */
        ClienteDetalle: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento: string | null;
            /** Numero Documento */
            numero_documento: string | null;
            /** Telefono */
            telefono: string | null;
            /** Email */
            email: string | null;
            /** Ciudad */
            ciudad: string | null;
            /** Consentimiento */
            consentimiento: boolean;
            /** Archivado */
            archivado: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Pais Id */
            pais_id: number | null;
            /** Canal Id */
            canal_id: number | null;
            /** Observaciones */
            observaciones: string | null;
            /** Consentimiento Fecha */
            consentimiento_fecha: string | null;
            /**
             * Grupos
             * @default []
             */
            grupos: components["schemas"]["GrupoSalida"][];
            /**
             * Solicitantes
             * @description Propios y de sus grupos
             * @default []
             */
            solicitantes: components["schemas"]["SolicitanteSalida"][];
        };
        /** ClienteEditar */
        ClienteEditar: {
            /** Nombre */
            nombre?: string | null;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Numero Documento */
            numero_documento?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Pais Id */
            pais_id?: number | null;
            /** Canal Id */
            canal_id?: number | null;
            /** Consentimiento */
            consentimiento?: boolean | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** ClienteSalida */
        ClienteSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento: string | null;
            /** Numero Documento */
            numero_documento: string | null;
            /** Telefono */
            telefono: string | null;
            /** Email */
            email: string | null;
            /** Ciudad */
            ciudad: string | null;
            /** Consentimiento */
            consentimiento: boolean;
            /** Archivado */
            archivado: boolean;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** CodigoEntrada */
        CodigoEntrada: {
            /**
             * Codigo
             * @description Código de 6 dígitos de la aplicación autenticadora
             */
            codigo: string;
        };
        /** CoincidenciaSalida */
        CoincidenciaSalida: {
            /** Cliente Id */
            cliente_id: number;
            /** Nombre */
            nombre: string;
            /**
             * Confianza
             * @enum {string}
             */
            confianza: "alta" | "media" | "baja";
            /** Criterios */
            criterios: string[];
            /** Explicacion */
            explicacion: string;
            /** Parecido Nombre */
            parecido_nombre: number;
            /** Archivado */
            archivado: boolean;
            /**
             * Posible Familiar
             * @description Comparte datos pero el nombre de pila es distinto
             * @default false
             */
            posible_familiar: boolean;
        };
        /** DesafioMfa */
        DesafioMfa: {
            /**
             * Requiere Mfa
             * @default true
             * @constant
             */
            requiere_mfa: true;
            /** Token Mfa */
            token_mfa: string;
        };
        /** EstadoPosible */
        EstadoPosible: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
        };
        /**
         * Ficha360
         * @description Todo lo que hoy está repartido entre tres archivos, en una sola respuesta.
         */
        Ficha360: {
            cliente: components["schemas"]["ClienteDetalle"];
            resumen: components["schemas"]["ResumenFicha"];
            /**
             * Tramites
             * @default []
             */
            tramites: components["schemas"]["CasoSalida"][];
            /**
             * Citas
             * @default []
             */
            citas: components["schemas"]["CitaProxima"][];
            /**
             * Cronologia
             * @default []
             */
            cronologia: components["schemas"]["SucesoSalida"][];
            /**
             * Ve Tramites
             * @description False si el rol no tiene permiso de ver trámites
             */
            ve_tramites: boolean;
        };
        /** FusionEntrada */
        FusionEntrada: {
            /** Absorbido Id */
            absorbido_id: number;
            /**
             * Criterio
             * @default manual
             * @enum {string}
             */
            criterio: "documento" | "pasaporte" | "telefono" | "email" | "nombre" | "manual";
        };
        /** FusionSalida */
        FusionSalida: {
            /** Conservado Id */
            conservado_id: number;
            /** Absorbido Id */
            absorbido_id: number;
            /**
             * Movidos
             * @description Cuántos registros cambiaron de ficha, por tabla
             */
            movidos: {
                [key: string]: number;
            };
        };
        /** GrupoCrear */
        GrupoCrear: {
            /** Nombre */
            nombre: string;
            /** Cliente Contacto Id */
            cliente_contacto_id: number;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** GrupoSalida */
        GrupoSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Cliente Contacto Id */
            cliente_contacto_id: number;
            /** Observaciones */
            observaciones: string | null;
            /**
             * Solicitantes
             * @default []
             */
            solicitantes: components["schemas"]["SolicitanteSalida"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorialSalida */
        HistorialSalida: {
            /**
             * Titulo
             * @description Lo que pasó, en español y con los catálogos resueltos
             */
            titulo: string;
            /** Campo */
            campo: string;
            /** Valor Anterior */
            valor_anterior: string | null;
            /** Valor Nuevo */
            valor_nuevo: string | null;
            /** Usuario */
            usuario: string | null;
            /** Observacion */
            observacion: string | null;
            /**
             * Ocurrido En
             * Format: date-time
             */
            ocurrido_en: string;
        };
        /** ItemChecklist */
        ItemChecklist: {
            /** Item Id */
            item_id: number;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Obligatorio */
            obligatorio: boolean;
            /** Cumplido */
            cumplido: boolean;
        };
        /** LoginEntrada */
        LoginEntrada: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarcarItem */
        MarcarItem: {
            /** Cumplido */
            cumplido: boolean;
            /** Observacion */
            observacion?: string | null;
        };
        /** MfaInicioSalida */
        MfaInicioSalida: {
            /**
             * Secreto
             * @description Para escribirlo a mano si no se puede escanear el QR
             */
            secreto: string;
            /**
             * Uri
             * @description otpauth:// para generar el código QR
             */
            uri: string;
        };
        /** NotaCrear */
        NotaCrear: {
            /**
             * Tipo
             * @default nota
             * @enum {string}
             */
            tipo: "nota" | "llamada" | "whatsapp" | "correo" | "reunion";
            /** Asunto */
            asunto?: string | null;
            /** Cuerpo */
            cuerpo?: string | null;
        };
        /** NotaSalida */
        NotaSalida: {
            /** Id */
            id: number;
            /** Tipo */
            tipo: string;
            /** Asunto */
            asunto: string | null;
            /** Cuerpo */
            cuerpo: string | null;
            /**
             * Ocurrido En
             * Format: date-time
             */
            ocurrido_en: string;
        };
        /** Opcion */
        Opcion: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Codigo */
            codigo?: string | null;
            /** Pais Id */
            pais_id?: number | null;
        };
        /** PaginaCasos */
        PaginaCasos: {
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Tamano */
            tamano: number;
            /** Items */
            items: components["schemas"]["CasoSalida"][];
        };
        /** PaginaClientes */
        PaginaClientes: {
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Tamano */
            tamano: number;
            /** Items */
            items: components["schemas"]["ClienteSalida"][];
        };
        /** PasaporteSalida */
        PasaporteSalida: {
            /** Solicitante Id */
            solicitante_id: number;
            /**
             * Pasaporte
             * @description Valor completo. La consulta queda en la auditoría.
             */
            pasaporte: string;
        };
        /** PasswordTemporalSalida */
        PasswordTemporalSalida: {
            usuario: components["schemas"]["UsuarioSalida"];
            /**
             * Password Temporal
             * @description Se muestra una sola vez. Entregarla por un canal seguro.
             */
            password_temporal: string;
        };
        /** RecuperarEntrada */
        RecuperarEntrada: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** RestablecerEntrada */
        RestablecerEntrada: {
            /** Token */
            token: string;
            /** Nueva */
            nueva: string;
        };
        /** ResultadoBusqueda */
        ResultadoBusqueda: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "cliente" | "solicitante" | "tramite";
            /** Id */
            id: number;
            /** Titulo */
            titulo: string;
            /** Detalle */
            detalle: string;
            /** Ruta */
            ruta: string;
            /** Coincidio Por */
            coincidio_por: string;
        };
        /** ResultadoEntrada */
        ResultadoEntrada: {
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "aprobada" | "negada" | "proceso_administrativo" | "cancelado" | "no_continuo";
            /** Fecha */
            fecha?: string | null;
            /** Nota */
            nota?: string | null;
        };
        /** ResumenEstado */
        ResumenEstado: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Total */
            total: number;
        };
        /** ResumenFicha */
        ResumenFicha: {
            /** Personas */
            personas: number;
            /** Tramites Abiertos */
            tramites_abiertos: number;
            /** Tramites Total */
            tramites_total: number;
            /** Proxima Cita */
            proxima_cita: string | null;
            /** Ultimo Contacto En */
            ultimo_contacto_en: string | null;
            /** Dias Sin Contacto */
            dias_sin_contacto: number | null;
        };
        /** RolSalida */
        RolSalida: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Permisos */
            permisos: string[];
        };
        /** SegundoFactorEntrada */
        SegundoFactorEntrada: {
            /** Token Mfa */
            token_mfa: string;
            /**
             * Codigo
             * @description Código de 6 dígitos de la aplicación autenticadora
             */
            codigo: string;
        };
        /** SolicitanteCrear */
        SolicitanteCrear: {
            /** Grupo Id */
            grupo_id?: number | null;
            /** Cliente Id */
            cliente_id?: number | null;
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Numero Documento */
            numero_documento?: string | null;
            /** Pasaporte */
            pasaporte?: string | null;
            /** Fecha Nacimiento */
            fecha_nacimiento?: string | null;
            /** Nacionalidad */
            nacionalidad?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Relacion Con Cliente
             * @description titular, cónyuge, hijo, otro
             */
            relacion_con_cliente?: string | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** SolicitanteEditar */
        SolicitanteEditar: {
            /** Nombre */
            nombre?: string | null;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Numero Documento */
            numero_documento?: string | null;
            /** Pasaporte */
            pasaporte?: string | null;
            /** Fecha Nacimiento */
            fecha_nacimiento?: string | null;
            /** Nacionalidad */
            nacionalidad?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Relacion Con Cliente */
            relacion_con_cliente?: string | null;
            /** Observaciones */
            observaciones?: string | null;
        };
        /** SolicitanteSalida */
        SolicitanteSalida: {
            /** Id */
            id: number;
            /** Grupo Id */
            grupo_id: number | null;
            /** Cliente Id */
            cliente_id: number | null;
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento: string | null;
            /** Numero Documento */
            numero_documento: string | null;
            /**
             * Pasaporte
             * @description Enmascarado: solo los últimos caracteres
             */
            pasaporte: string | null;
            /** Fecha Nacimiento */
            fecha_nacimiento: string | null;
            /** Nacionalidad */
            nacionalidad: string | null;
            /** Telefono */
            telefono: string | null;
            /** Email */
            email: string | null;
            /** Relacion Con Cliente */
            relacion_con_cliente: string | null;
        };
        /** SucesoSalida */
        SucesoSalida: {
            /**
             * Cuando
             * Format: date-time
             */
            cuando: string;
            /**
             * Tipo
             * @description 'sistema' para lo que registró el sistema; si no, el tipo de la nota
             */
            tipo: string;
            /** Titulo */
            titulo: string;
            /** Detalle */
            detalle: string | null;
            /** Usuario */
            usuario: string | null;
            /** Caso Id */
            caso_id: number | null;
        };
        /** TokenSalida */
        TokenSalida: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expira En Segundos */
            expira_en_segundos: number;
        };
        /** UsuarioAsignable */
        UsuarioAsignable: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Rol */
            rol: string;
        };
        /** UsuarioCrear */
        UsuarioCrear: {
            /** Nombre */
            nombre: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Rol */
            rol: string;
            /**
             * Alcance
             * @default todos
             * @enum {string}
             */
            alcance: "todos" | "asignados" | "propios";
        };
        /** UsuarioEditar */
        UsuarioEditar: {
            /** Nombre */
            nombre?: string | null;
            /** Rol */
            rol?: string | null;
            /** Activo */
            activo?: boolean | null;
            /** Alcance */
            alcance?: ("todos" | "asignados" | "propios") | null;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Alcance */
            alcance: string;
            /** Activo */
            activo: boolean;
            /** Mfa Habilitado */
            mfa_habilitado: boolean;
            /** Debe Cambiar Password */
            debe_cambiar_password: boolean;
            /** Bloqueado */
            bloqueado: boolean;
            /** Ultimo Acceso */
            ultimo_acceso: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificarDuplicados
         * @description Se consulta mientras se escribe la ficha, antes de guardarla.
         */
        VerificarDuplicados: {
            /** Nombre */
            nombre: string;
            /** Tipo Documento */
            tipo_documento?: string | null;
            /** Numero Documento */
            numero_documento?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Email */
            email?: string | null;
            /** Pasaporte */
            pasaporte?: string | null;
            /** Excluir Id */
            excluir_id?: number | null;
        };
        /** YoSalida */
        YoSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Alcance */
            alcance: string;
            /** Permisos */
            permisos: string[];
            /** Mfa Habilitado */
            mfa_habilitado: boolean;
            /** Debe Cambiar Password */
            debe_cambiar_password: boolean;
            /**
             * Mfa Requerido
             * @description Su rol exige doble factor y aún no lo activa
             */
            mfa_requerido: boolean;
            /** Ultimo Acceso */
            ultimo_acceso: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"] | components["schemas"]["DesafioMfa"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verificar_mfa_api_v1_auth_mfa_verificar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegundoFactorEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yo_api_v1_auth_yo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YoSalida"];
                };
            };
        };
    };
    iniciar_mfa_api_v1_auth_mfa_iniciar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaInicioSalida"];
                };
            };
        };
    };
    confirmar_mfa_api_v1_auth_mfa_confirmar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodigoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_password_api_v1_auth_cambiar_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioPasswordEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recuperar_api_v1_auth_recuperar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecuperarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_api_v1_auth_restablecer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestablecerEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_casos_get: {
        parameters: {
            query?: {
                estado?: string | null;
                responsable_id?: number | null;
                pais_id?: number | null;
                fuente?: ("saas" | "manual" | "hibrido") | null;
                sin_asignar?: boolean;
                sin_venta?: boolean;
                incluir_finalizados?: boolean;
                texto?: string | null;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaCasos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_api_v1_casos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasoCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumen_api_v1_casos_resumen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenEstado"][];
                };
            };
        };
    };
    detalle_api_v1_casos__caso_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_api_v1_casos__caso_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasoEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_estado_api_v1_casos__caso_id__estado_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioEstado"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_resultado_api_v1_casos__caso_id__resultado_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultadoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasoDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_api_v1_casos__caso_id__historial_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorialSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agendar_cita_api_v1_casos__caso_id__citas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitaCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_cita_api_v1_citas__cita_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cita_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitaEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    marcar_checklist_api_v1_casos__caso_id__checklist__item_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarItem"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogos_api_v1_catalogos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogos"];
                };
            };
        };
    };
    listar_api_v1_clientes_get: {
        parameters: {
            query?: {
                /** @description Nombre, documento, teléfono o correo */
                texto?: string | null;
                archivados?: boolean;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaClientes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_api_v1_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verificar_duplicados_api_v1_clientes_verificar_duplicados_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarDuplicados"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoincidenciaSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_api_v1_clientes__cliente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_api_v1_clientes__cliente_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteDetalle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archivar_api_v1_clientes__cliente_id__archivar_post: {
        parameters: {
            query?: {
                archivado?: boolean;
            };
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicados_de_api_v1_clientes__cliente_id__duplicados_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoincidenciaSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fusionar_api_v1_clientes__cliente_id__fusionar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FusionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FusionSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_grupo_api_v1_grupos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrupoCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_solicitantes_api_v1_solicitantes_get: {
        parameters: {
            query?: {
                cliente_id?: number | null;
                grupo_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitanteSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_solicitante_api_v1_solicitantes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitanteCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitanteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_por_pasaporte_api_v1_solicitantes_buscar_get: {
        parameters: {
            query: {
                pasaporte: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitanteSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_solicitante_api_v1_solicitantes__solicitante_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solicitante_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitanteEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitanteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_pasaporte_api_v1_solicitantes__solicitante_id__pasaporte_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                solicitante_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasaporteSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_api_v1_buscar_get: {
        parameters: {
            query: {
                /** @description Nombre, teléfono, documento, correo, pasaporte, DS-160 o n.º de solicitud del SaaS */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoBusqueda"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ficha_360_api_v1_clientes__cliente_id__ficha_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ficha360"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anotar_cliente_api_v1_clientes__cliente_id__notas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotaCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anotar_caso_api_v1_casos__caso_id__notas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caso_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotaCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_usuarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"][];
                };
            };
        };
    };
    crear_api_v1_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCrear"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_api_v1_usuarios__usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioEditar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restablecer_password_api_v1_usuarios__usuario_id__restablecer_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reiniciar_mfa_api_v1_usuarios__usuario_id__reiniciar_mfa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordTemporalSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asignables_api_v1_usuarios_asignables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioAsignable"][];
                };
            };
        };
    };
    roles_api_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolSalida"][];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
